spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: 디비에 맞는 방언 입력.
#        show_sql: true
        format_sql: true

# page global default 변경
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true # 1부터 시작하는 인덱스 파라미터가 된다.
        # 근데 여기에는 한계가 있다. 밑의 pageable 의 데이터들이 안 맞게 된다. pageNumber도 0으로 되어있고 뭐 그렇다

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace